### ISSUE TITLE
Trailing slash on URL causes warning about push notifications. 

### ISSUE THREAD

**Issue by elnjensen** [aditmer/NightscoutHybridMobile#48]
When setting up a new iOS device, I entered my NS site URL with a trailing slash, e.g., `https://mysite.herokuapp.com/` and it told me 'Your Nightscout website does not have azurepush enabled' though I do have it enabled and working.  Removing the slash fixed the problem.  Perhaps the code could recognize either format?  I'm on heroku, FWIW.

**Comment by aditmer** [comment]
I am pushing a new build that removes a trailing / automatically.  I think the issue was caused by how I was appending web service URL calls.  For example, I would check for the azurepush variable in your enable string like this:   string sRestUrl = URL + "/api/v1/status.json";

So, if URL had a trailing / it would look like this:  https://yoururl.herokuapp.com//api/v1/status.json

So, I simply look for a tailing / and remove it.
